### ISSUE TITLE
Instructions for running locally by new developer

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#156]
I would expect to be able to type:
```
git clone https://github.com/tijlleenders/ZinZen.git
cd ZinZen
npm start
```

This does not work.
I get an error: sh: 1: react-scripts: not found
After a quick google I know I have to do an 'npm install' since the node_modules aren't there yet on a fresh clone.
It fails the first time with a bunch of error messages.
I retry 'npm install'.
Then it takes forever to download Cypress.
Then it fails with error message: The Cypress App could not be downloaded.
Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

What should be added to the code / instructions to make it not only smooth - but the smoothest experience possible?

**Comment by pulkitvyas08** [comment]
It worked fine for me even though I am behind a very strict university firewall. I'll try to reproduce this issue and see what can be done

**Comment by tijlleenders** [comment]
No ```npm install``` required?  
Here's what I see.
Maybe it's only my machine...  
I'm running the latest Ubuntu from the Microsoft store on WSL2.  
```
uname -a
Linux DESKTOP-J8F7D8U 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
 npm run dev

> zinzen-frontend@0.1.0 dev /home/tijl/test/ZinZen
> vite

sh: 1: vite: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! zinzen-frontend@0.1.0 dev: `vite`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the zinzen-frontend@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

After running ```npm install``` it shows this:  
```
added 1916 packages from 851 contributors and audited 1949 packages in 143.354s

212 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
  
After that I still get error message:  
```
zinzen-frontend@0.1.0 dev /home/tijl/test/ZinZen
> vite

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tijl/test/ZinZen/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zinzen-frontend@0.1.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zinzen-frontend@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```  

Additional logging:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle zinzen-frontend@0.1.0~predev: zinzen-frontend@0.1.0
6 info lifecycle zinzen-frontend@0.1.0~dev: zinzen-frontend@0.1.0
7 verbose lifecycle zinzen-frontend@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle zinzen-frontend@0.1.0~dev: PATH:[redacted]
9 verbose lifecycle zinzen-frontend@0.1.0~dev: CWD: /home/tijl/test/ZinZen
10 silly lifecycle zinzen-frontend@0.1.0~dev: Args: [ '-c', 'vite' ]
11 silly lifecycle zinzen-frontend@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle zinzen-frontend@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: zinzen-frontend@0.1.0 dev: `vite`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zinzen-frontend@0.1.0
15 verbose cwd /home/tijl/test/ZinZen
16 verbose Linux 5.10.16.3-microsoft-standard-WSL2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error zinzen-frontend@0.1.0 dev: `vite`
22 error Exit status 1
23 error Failed at the zinzen-frontend@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mallikarai05** [comment]
No sorry
I thought it was already there.

**Comment by mallikarai05** [comment]
I'll look into the error once

**Comment by tijlleenders** [comment]
Since a few friends of @mallikarai05 had no issues it's probably just my setup with WSL2 Ubuntu under Linux.
