### ISSUE TITLE
GoalsParser unit test not working

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#345]
Please make sure to test all unit tests locally before pushing to main as there is no testing suite as mentioned in #342.

I just found out that the `GoalsParser.test.ts` is not working as expected. Not just that it's not working but there are compilation errors blocking it. Please read the error stack below for detailed information and use `npm test --[file path]` to run the test locally before making a PR, thanks.

```
 FAIL  src/components/GoalsComponents/GoalParser.test.ts
  ● Test suite failed to run

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

       7 | });
       8 |
    >  9 | const [outputObject, setOutputObject] = useState([]);
         |                                         ^
      10 |
      11 | function getGoalObject() {}
      12 |

      at resolveDispatcher (node_modules/react/cjs/react.development.js:1476:13)
      at useState (node_modules/react/cjs/react.development.js:1507:20)
      at Object.<anonymous> (src/components/GoalsComponents/GoalParser.test.ts:9:41)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        14.305 s
Ran all test suites matching /.\\src\\components\\GoalsComponents\\GoalParser.test.ts/i.
```

**Comment by GithinjiHans** [comment]
I changed the code...

**Comment by GithinjiHans** [comment]
The bug was the useState so I corrected it before making the test pass first.... It's working now

**Comment by pulkitvyas08** [comment]
Yupp, that's correct. Checked the latest commit and it's working, thanks for notifying
