### ISSUE TITLE
App.test.tsx failing due to import error

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#346]
Seems like for Jest unit testing we might need to add path alias support explicitly. Find the error in the below error stack trace.

```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Cannot find module '@store' from 'src/App.tsx'

    Require stack:
      src/App.tsx
      src/App.test.tsx

      4 | import { Container, Row } from 'react-bootstrap';
      5 |
    > 6 | import { darkModeState, themeSelectionState, languageSelectionState } from '@store';
        | ^
      7 |
      8 | import { LandingPage } from '@pages/LandingPage/LandingPage';
      9 | import { LandingPageThemeChoice } from '@pages/ThemeChoicePage/LandingPageThemeChoice';

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/App.tsx:6:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.182 s
Ran all test suites matching /.\\src\\App.test.tsx/i.
```

**Comment by GithinjiHans** [comment]
App.test.tsx was deleted...It could be working by now since the import errors are solved
